### ISSUE TITLE
Module "pretty" name should be "ShareThis" - not "Sharethis".

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/sharethis#1]
That is the way the name of the original module is written. I have corrected the "A port of the ShareThis Drupal 7 module to BackdropCMS" repo description, But there are still some "Sharethis" instances in the README.md that I guess would need a PR ...which I don't know how to do.

Should be a simple search and replace.

**Comment by jenlampton** [comment]
> which I don't know how to do.

You should be able to do this via the UI now @klonos.  On the right hand side of [this page](https://github.com/backdrop-contrib/sharethis/blob/1.x-1.x/readme.md) do you see a pencil icon to edit?

After you use that to make necessary changes, at the bottom of the form there's an option to put those changes into a PR on the project :)

![screen shot 2016-12-24 at 2 20 12 pm](https://cloud.githubusercontent.com/assets/397895/21468792/48a73ee0-c9e4-11e6-804f-1ce54bf2fb46.png)

**Comment by klonos** [comment]
Yeah, I filed that issue before I got "initiated" to the magic that is the GitHub UI 😄 

...I see you already took care of this. Thanx 👍

**Comment by jenlampton** [comment]
the name has been updated in the 2.x branch.
