### ISSUE TITLE
Facebook share and like widgets don't work.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/sharethis#19]
I can use the twitter and email widgets to share content, but the facebook share opens and closes a window (you just see it for a second) and goes away without sharing the content.

Like button flashes change from 0 to 1 but then goes back to 0.

I opened chrome console, did not see any js errors.  I'm using the `bootstrap_lite` theme, I tried in basis as well, but same problems.

That is the extent of the troubleshooting I've done so far.  @jenlampton is facebook share widget working for you?

**Comment by jenlampton** [comment]
Sharing to facebook works for me. Were you logged into facebook when you tried to share? I wonder if the login-redirect circle is part of the problem.

**Comment by serundeputy** [comment]
yes; logged into facebook.

**Comment by jenlampton** [comment]
Are you on HTTP or HTTPS?

**Comment by serundeputy** [comment]
local http;

**Comment by serundeputy** [comment]
This is working for me on another computer .... I think must have been specific to that local set up.

the domain i was using was `calculation` i.e. not `calculation.dev` or .com or whatever so maybe sharethis checks for at least a plausible domain, but in any event not a module problem :).

closing.
