### ISSUE TITLE
Migrate to inline buttons

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/sharethis#24]
It looks like ShareThis has upgraded their buttons, and they've got a migration guide from their legacy buttons here: https://www.sharethis.com/support/installation/migrate-from-sharethis-legacy-buttons-to-inline-buttons/

Can we update this module to support the new buttons?

**Comment by jenlampton** [comment]
Yes, thanks for the link! :)

**Comment by jenlampton** [comment]
I've created a 1.x-1.3.x branch for the new inline buttons. This version of the module is much simpler, so I cleaned up a lot of the cruft in the process.

**Comment by helenasue** [comment]
Chiming in: fwiw, the new inline ShareThis button aren't accessible AT ALL. They have zero keyboard or screen reader accessibility. I've reached out to them and offered to help them fix it, but they have a long history of downplaying a11y, so it might not help.
